version: "3.9"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /var/www/nginx-php/html:/var/www/html
      - /var/www/nginx-php/conf/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8-fpm
    volumes:
      - /var/www/nginx-php/html:/var/www/html
